name: Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20', '22']

    container:
      image: node:${{ matrix.node }}-alpine

    steps:
    - uses: actions/checkout@v4
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test
